name: news_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  intl: any
  floor: ^1.4.2
  retrofit: ^4.0.3
  cached_network_image: ^3.3.0
  ionicons: ^0.2.2
  url_launcher: ^6.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  uni_links: ^0.5.1
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.5
  floor_generator: ^1.4.2
  build_runner: ^2.4.7
  change_app_package_name: ^1.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
